spring.application.name=restaurante

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.spwwvwvsvhnmhbmnqbvr
spring.datasource.password=ENGENHARIA2026

spring.jpa.hibernate.ddl-auto=update
